export const TABLE_NAMES = {
  USERS: process.env.USERS_TABLE!,
  LEAGUES: process.env.LEAGUES_TABLE!,
  LEAGUE_MEMBERS: process.env.LEAGUE_MEMBERS_TABLE!,
  ROUNDS: process.env.ROUNDS_TABLE!,
  ROUND_PARTICIPANTS: process.env.ROUND_PARTICIPANTS_TABLE!,
  MATCHES: process.env.MATCHES_TABLE!,
  SCORES: process.env.SCORES_TABLE!,
  CONVERSATIONS: process.env.CONVERSATIONS_TABLE!,
  CHAT_MESSAGES: process.env.CHAT_MESSAGES_TABLE!,
  FOLLOWS: process.env.FOLLOWS_TABLE!,
  PAYMENTS: process.env.PAYMENTS_TABLE!,
  NOTIFICATIONS: process.env.NOTIFICATIONS_TABLE!,
  WEBSOCKET_CONNECTIONS: process.env.WEBSOCKET_CONNECTIONS_TABLE!,
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const PAGINATION = {
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

export const CURRENCY = {
  DEFAULT: 'GBP',
};

export const MATCH_CONFIG = {
  MAX_GROUP_SIZE: 8,
};
